[package]
name = "atcoder_client"
version = "0.1.0"
edition = "2024"
publish = false
authors = ["yiwiy9"]

[dependencies]
chrono = "0.4"
regex = "1.11"
reqwest = { version = "0.12", features = ["cookies", "gzip"] }
scraper = "0.23"
thiserror = "2.0"
