pub const ATCODER_SESSION_ENV: &str = "ATCODER_REVEL_SESSION";
pub const DYNAMODB_TABLE_ENV: &str = "DYNAMODB_TABLE_NAME";
pub const ATCODER_CRAWL_SLEEP_MILLIS: u64 = 300;
pub const ATCODER_CRAWL_MAX_RETRIES: usize = 3;
pub const ATCODER_CRAWL_RETRY_SLEEP_MILLIS: u64 = 60_000;
pub const MAX_IN_MEMORY_SUBMISSIONS: usize = 10_000;
